name: "Naja Design Regress"
description: "Synthesize Verilog with Yosys, and test and analyze with Najaeda."
author: "najaeda"
branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  yosys_script:
    description: "Path to the Yosys input script"
    required: true
  synth_root:
    description: "Path to the root of the design files"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  #inputs:
  #  yosys_script: ${{ inputs.yosys_script }}
  #  synth_root: ${{ inputs.synth_root }}
  #steps:
  #  - name: Install Yosys
  #    shell: bash
  #    run: |
  #      sudo apt update
  #      sudo apt install -y yosys

#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: "3.10"
#
#    - name: Install Python dependencies
#      shell: bash
#      run: |
#        pip install --upgrade pip
#        pip install najaeda
#        #pip install -r ${{ github.action_path }}/requirements.txt
#
#    - name: Run Yosys synthesis
#      shell: bash
#      env:
#        SYNTH_ROOT: ${{ inputs.synth_root }}
#      run: |
#        mkdir -p yosys
#        echo "Synthesis root: $SYNTH_ROOT"
#        cd yosys; yosys -c ${{ inputs.yosys_script }}
#
#    - name: Analyze synthesized netlist with Najaeda
#      shell: bash
#      run: |
#        python ${{ github.action_path }}/scripts/analyze.py build/netlist.v > stats.json
#
#    - name: Generate dashboard
#      shell: bash
#      run: |
#        python ${{ github.action_path }}/scripts/dashboard.py stats.json ${{ inputs.output-dir }}
#