name: "Naja Design Regress"
description: "Synthesize Verilog with Yosys, and test and analyze with Najaeda."
author: "najaeda"
branding:
  icon: "bar-chart-2"
  color: "blue"

inputs:
  mode:
    description: "Mode of operation: 'direct' for direct synthesis, 'orfs' for ORFS synthesis"
    required: true
    default: "orfs"
  design_home:
    description: "Path to the design home"
    required: true
  design_config:
    description: "Path to the design config"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mode }}
    - ${{ inputs.design_home }}
    - ${{ inputs.design_config }}