name: "Test naja-action"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      verilog-files:
        description: "Verilog file glob"
        required: true
        default: "src/*.v"
      top-module:
        description: "Top-level module name"
        required: true
        default: "top"

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run naja-action
        uses: ./.  # local composite action
        with:
          yosys-script: benchs/black_parrot/yosys.ys
