name: "Test naja-action in orfs mode"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #workflow_dispatch:
  #  inputs:
  #    verilog-files:
  #      description: "Verilog file glob"
  #      required: true
  #      default: "src/*.v"
  #    top-module:
  #      description: "Top-level module name"
  #      required: true
  #      default: "top"

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run naja-action
        uses: ./.  # local composite action
        with:
          mode: "orfs"
          design_home: "benchs/black_parrot"
          design_config: "benchs/black_parrot/config.mk"